name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ toolchain
        uses: actions/setup-cpp@v2
        with:
          cpp-version: '14'

      - name: Build and test
        run: |
          g++ -o snake SnakeGame.cpp
          ./snake







   




  

    
 
    




     


